### ISSUE TITLE
Error talking to pass

### ISSUE THREAD

**Issue by efenex** [dannyvankooten/chrome-gopass#8]
Installed the go binary, unzipped the crx and loaded it into chromium. When I try to use the extension, all I see is "Error talking to pass".

Running the gopass-linux64 binary manually does not give any errors, but I have no idea how to test/validate it's functionality.

Potential issue: I use pass with a Yubikey, which means it should prompt for my pin whenever attempting to get a password. Note that at least `pass list` and `pass find` are possible without any key/pin, so these should work.

**Comment by dannyvankooten** [comment]
Hey @efenex ,

Did you run the `install.sh` file to install the native host application? What this does is copy a file from the zip package to your Chrome config directory. 

As I type this I realise you're on Chromium, for which the config directory may differ slightly from Chrome so that running `./install.sh` won't really work. I'll look into that right away.

**Comment by efenex** [comment]
I did run install.sh, and your suspicion is correct, it seems to have installed the file to:

 ~/.config/google-chrome/NativeMessagingHosts/com.dannyvankooten.gopass.json

I also see that it refers to a binary called "gopass", while the one I have is "gopass-linux64".

I'll try with your latest update.

**Comment by dannyvankooten** [comment]
Hey @efenex,

The installation script needed a modification for Chromium, it should work better with the latest modifications. Please note that you may have to re-download the release packages for this to work, I've updated them with the latest changes.

**Comment by efenex** [comment]
cd ~
git clone https://github.com/dannyvankooten/chrome-gopass.git
./install.sh                                                                                                                                                                                      Select your browser:
1) Chrome
2) Chromium
3) Firefox
1-3: 2
Installing Chrome / Chromium host config
cp: cannot stat '/home/efenex/chrome-gopass/chrome-host.json': No such file or directory

**Comment by efenex** [comment]
I replaced the "-" with "/" to refer to the correct paths for the json file, now install.sh works. I do see it has the following in the json file:

  "path": "/home/efenex/chrome-gopass/gopass",

While now my binary is called "gopass.go" as per the git checkout (as opposed to "gopass-linux64" from the zip file earlier).

**Comment by dannyvankooten** [comment]
The `gopass.go` file is the uncompiled version of the binary. It's because cloning the repository won't give you the files ready for distribution. That's also why `chrome-host.json` is in the "wrong" directory.

The following link will get you a package meant for distribution: https://github.com/dannyvankooten/chrome-gopass/releases/download/1.0/gopass-linux64.zip

**Comment by efenex** [comment]
Just realised the same, let me try the package :-)

**Comment by efenex** [comment]
OK, no more error on install.sh. Still get "Error talking to pass".

I updated the path in the json file to point to "gopass-linux64" instead of "gopass" and the error disappears. Now I just get "No passwords found for X", no matter what I input though.

**Comment by efenex** [comment]
Ahhhh I see, no my passwords are not structured like that. I assumed it would do a 'pass find X' and give me a number of entries to select based on that.

I actually have:

```
~/.password-store
           /web
                      /website.com
           /irc
           /email
                      /user@hotmail.com
```

And multiple users for the same site are typically stored in the same file (in order to keep usernames secure, I prefer not to expose them in the filenames - while I don't care about the website name itself).

**Comment by dannyvankooten** [comment]
Hmm, using `pass find` may be a better idea than the current glob-approach, I'd have to have to a play with it. 

I totally get the username thing, I plan to allow for a little more flexibility later on . Perhaps the ability to include the username on the 2nd line of the password file or prefixed with `login:` would be a nice way to tackle this.  I

I built this over the weekend so it's still a little rough around the edges, as you noticed. :-)

**Comment by efenex** [comment]
Yeah no problem, happy to see someone work on it! :-)

Am currently using the approach of username on 2nd line of password file, and when I have multiple accounts I leave an empty line and add another block of password, username, (optional) extra details

I'll keep an eye on progress and give it another try if you implement find functionality!

**Comment by dannyvankooten** [comment]
Hey @efenex,

Wanted to give you a quick headsup that the extension now allows for a more flexible directory structure. It will search for the given string in up to 3 directories deep now.

It will then parse the password file for lines starting with `login:` or `username:`. If no such line is found, the filename is assumed to be the username.

![image](https://cloud.githubusercontent.com/assets/885856/20154600/644f8772-a6c8-11e6-9f3b-2fe62993e665.png)

It does not yet support multiple passwords in 1 file though.
